version: "3.9"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"

  haproxy:
    image: haproxy:2.9
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

  api1:
    build: ./services/api

  api2:
    build: ./services/api

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: servis
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass

  rabbitmq:
    image: rabbitmq:3-management

  memcached:                 
    image: memcached:alpine