services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - haproxy
    networks:
      autoservis-net:
        aliases:
          - nginx

  haproxy:
    image: haproxy:2.9
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - api1
      - api2
    networks:
      autoservis-net:
        aliases:
          - haproxy

  api1:
    build: ./services/apissssss
    environment:
      - API_NAME=ap1
    networks:
      - autoservis-net

  api2:
    build: ./services/api
    environment:
      - API_NAME=ap2
    networks:
      - autoservis-net

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: servis
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    networks:
      - autoservis-net

  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - autoservis-net

  memcached:
    image: memcached:alpine
    networks:
      - autoservis-net

networks:
  autoservis-net:
    name: autoservis-net
    driver: bridge