version: "3.9"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - haproxy

  haproxy:
    image: haproxy:2.9
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - api1
      - api2

  api1:
    build: ./services/api
    environment:
      DATABASE_URL: postgresql+psycopg2://user:pass@db:5432/servis
    depends_on:
      - db

  api2:
    build: ./services/api
    environment:
      DATABASE_URL: postgresql+psycopg2://user:pass@db:5432/servis
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: servis
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - dbdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management

  memcached:
    image: memcached:alpine

volumes:
  dbdata:
