version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - haproxy
    networks:
      - autoservis-net

  haproxy:
    image: haproxy:2.9
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - api1
      - api2
    networks:
      - autoservis-net

  api1:
    build: ./services/api
    environment:
      API_NAME: ap1
      RABBIT_HOST: rabbitmq
      RABBIT_QUEUE: order_status_events
      SEED_ADMIN_EMAIL: admin@autoservis.com
      SEED_ADMIN_PASSWORD: admin123
    networks:
      - autoservis-net

  api2:
    build: ./services/api
    environment:
      API_NAME: ap2
      RABBIT_HOST: rabbitmq
      RABBIT_QUEUE: order_status_events
      SEED_ADMIN_EMAIL: admin@autoservis.com
      SEED_ADMIN_PASSWORD: admin123
    networks:
      - autoservis-net
  worker:
    build: ./services/api
    command: ["python", "-u", "worker.py"]
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_QUEUE: order_status_events
      BOSS_EMAIL: tomc.matija@gmail.com
      EMAIL_FROM: smiklosevic.smm@gmail.com
      EMAIL_PASS: luhnaylpbgiwfxvk
    depends_on:
      - rabbitmq
    networks:
      - autoservis-net

  postfix-relay:
    build: ./services/postfix-relay
    volumes:
      - ./services/postfix-relay/resolv.conf:/etc/resolv.conf:ro
    networks:
      - autoservis-net
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: servis
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    networks:
      - autoservis-net

  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - autoservis-net

  memcached:
    image: memcached:alpine
    networks:
      - autoservis-net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - autoservis-net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - autoservis-net

  airflow-webserver:
    image: apache/airflow:2.7.1
    restart: always
    ports:
      - "8081:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://user:pass@db:5432/servis
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW_UID: 50000
      AIRFLOW_GID: 50000
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/data:/opt/airflow
    command: webserver
    networks:
      - autoservis-net

  airflow-scheduler:
    image: apache/airflow:2.7.1
    restart: always
    depends_on:
      - airflow-webserver
      - db
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://user:pass@db:5432/servis
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW_UID: 50000
      AIRFLOW_GID: 50000
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/data:/opt/airflow
    command: scheduler
    networks:
      - autoservis-net

  airflow-exporter:
    build: ./airflow-exporter
    environment:
      AIRFLOW_BASE_URL: http://airflow-webserver:8080
      AIRFLOW_USERNAME: admin
      AIRFLOW_PASSWORD: admin
    depends_on:
      - airflow-webserver
    networks:
      - autoservis-net
    ports:
      - "9112:9112"



networks:
  autoservis-net:
    driver: bridge
