global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api'
    metrics_path: /metrics
    static_configs:
      - targets: ['api1:8000', 'api2:8000']

  - job_name: 'airflow'
    static_configs:
      - targets: ['airflow-exporter:9112']
